### ISSUE TITLE
data set logistic regression Classification

### ISSUE THREAD

**Issue by orlandombaa** [ashwinraj-in/MachineLearningRecipes#1]
Hello Ashwin 

Thank you for your articles. I am reading one of your articles related to logistic regression for clasification. However, I don´t find the dataset that you used in that example.  

Can you share us this dataset?

Best regrads, 
Orlando

**Comment by thisisashwinraj** [comment]
Hi Orlando,

Really appreciate you taking out time to read the article. 
You can download the dataset for building the logistic regression model from [here](https://www.kaggle.com/code/elikakarami/framingham-heart-disease-lr/data)

If you have any more doubts, feel free to reach out.

Best and Regards,
Ashwin
